name: HTX-assessment
dependencies:
- python=3.9
- pandas
- numpy
- matplotlib
- seaborn
- scikit-learn
- ipykernel
- pip:
  - fastapi
  - uvicorn
  - pillow
  - torch
  - torchvision
  - slowapi
  - pyyaml
  - tqdm
  - opencv-python
  - albumentations
  - mlflow